"use client";

import Header from "@/components/header/Header";
import Footer from "@/components/footer/Footer";
import ReduxProvider from "@/redux/ReduxProvider";
import { Toaster } from "react-hot-toast";

// export const metadata = {
//   title: "Fire Cutter",
//   description: "Generated by jhf",
// };

export default function PrimaryLayout({ children }) {
  return (
    <ReduxProvider>
      <Header />
      <div className="w-[90vw] md:w-[90vw] lg:w-[65vw] mx-auto">{children}</div>
      <Footer />
      <Toaster />
    </ReduxProvider>
  );
}
